name: Build
on: [push, workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          # 1. Створюємо папку для SDK заздалегідь, щоб прийняти ліцензії
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          
          # 2. Запускаємо чисту збірку без 'yes |', 
          # але з налаштуваннями пам'яті всередині самого buildozer
          buildozer -v android debug
        env:
          # Обмежуємо Gradle, щоб він не займав усю пам'ять сервера
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2g"
          # Приймаємо ліцензії автоматично через змінну оточення
          BUILDOZER_ALLOW_ORG_GRADLE_PROJECT_ANDROID_SKIP_SDK_READ: 1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TowerDefense
          path: bin/*.apk
