name: Android Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # МЫ МЕНЯЕМ ВЕРСИЮ UBUNTU НА БОЛЕЕ СТАРУЮ И СТАБИЛЬНУЮ

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade pip setuptools Cython==0.29.33 buildozer

      - name: Build with Buildozer
        run: buildozer android debug